DROP TABLE IF EXISTS students;
CREATE TABLE students(
  id SERIAL4 PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  house VARCHAR(255) NOT NULL,
  age INT2 NOT NULL
);
